<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sElePHPone%s'), '<span class="tr-blue">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! This is a community application build on %s'), '<span class="tr-blue">Tropo</span>') ?></p>
    <p><a class="btn btn-primary btn-lg" href="https://tropo.com" rel="nofollow" target="_blank"><?php echo $this->translate('Learn more about Tropo') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-leaf"></span>&nbsp;<?php echo $this->translate('The idea') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('ElePHPone started as an idea to share the community quotes beyond the reach of our community, using something as simple as a phone. As the proof-of-concept was build it was clear there was so much more we could do with it, so we decided to build a true community communication application using %s.'), '<a class="tr-blue" href="https://www.tropo.com/" rel="nofollow" target="_blank">Tropo</a>') ?></p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('The idea explained') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-phone"></span>&nbsp;<?php echo $this->translate('Call the community!') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Several members of the PHP community have recorded a message for you so you learn why this community is so special, strong and powerful. Now, the PHP community is only a phone call away, giving you wisdom and advice. Learn more about these people who welcome you to the PHP community')) ?></p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Get to know the PHP community') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-heart"></span>&nbsp;<?php echo $this->translate('Thanks to Tropo') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('I would like to express my sincere gratitude to %s and %s for making it possible for me to build and share this application. If you\'re looking for a phone service to build or extend your application, go check out %s for more details and a free trial.'), '<a class="tr-blue" href="https://www.cisco.com" target="_blank" rel="nofollow">Cisco</a>', '<a class="tr-blue" href="https://www.tropo.com" target="_blank" rel="nofollow">Tropo</a>', '<a class="tr-blue" href="https://www.tropo.com" target="_blank" rel="nofollow">Tropo</a>') ?></p>
                <p><a class="btn btn-primary pull-right" href="https://www.tropo.com" rel="nofollow" target="_blank"><?php echo $this->translate('Learn more about Tropo') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
